#!/bin/sh
set -eux

nvidia_dir=/lib/modules/*/kernel/nvidia-*
# Check nvidia_dir
[ -e $nvidia_dir/bits/SHA256SUMS ]

if ! cmp -s $nvidia_dir/bits/SHA256SUMS $SNAP_COMMON/nvidia-driver/bits/SHA256SUMS
then
    rm -rf $SNAP_COMMON/nvidia-driver
    mkdir -p $SNAP_COMMON/nvidia-driver
    cp -r $nvidia_dir/bits $SNAP_COMMON/nvidia-driver/
    cd $SNAP_COMMON/nvidia-driver/bits
    sed -i 's|/usr/bin/ld.bfd|ld.bfd|' BUILD
    sh BUILD
fi

snapctl kmod insert nvidia-drm
snapctl kmod insert nvidia-uvm

# device_add, which would create these is not available to proprietary modules
# thus nvidia.ko cannot create these
# i wish there was `snapctl mknod`
mknod -m 666 /dev/nvidia0 c 195 0 || echo Need mknod
mknod -m 666 /dev/nvidiactl c 195 255 || echo Need mknod
mknod -m 666 /dev/nvidia-modeset c 195 254 || echo Need mknod

major=$(sed -n 's|^\([0-9]*\) nvidia-uvm$|\1|p' /proc/devices)
if [ -n "$major" ]; then
    mknod -m 666 /dev/nvidia-uvm c $major 0 || echo Need mknod
    mknod -m 666 /dev/nvidia-uvm-tools c $major 1 || echo Need mknod
fi
