#!/bin/sh
set -eux

nvidia_dir=/lib/modules/*/kernel/nvidia-*
# Check nvidia_dir
[ -e $nvidia_dir/bits/SHA256SUMS ]

if ! cmp -s $nvidia_dir/bits/SHA256SUMS $SNAP_COMMON/nvidia-driver/bits/SHA256SUMS
then
    rm -rf $SNAP_COMMON/nvidia-driver
    mkdir -p $SNAP_COMMON/nvidia-driver
    cp -r $nvidia_dir/bits $SNAP_COMMON/nvidia-driver/
    cd $SNAP_COMMON/nvidia-driver/bits
    sed -i 's|/usr/bin/ld.bfd|ld.bfd|' BUILD
    sh BUILD
fi

snapctl kmod insert nvidia-drm || echo Needs snap connect nvidia-assemble:modprobe-nvidia
snapctl kmod insert nvidia-uvm || echo Needs snap connect nvidia-assemble:modprobe-nvidia
