#!/bin/sh
set -eux

nvidia_dirs=dirname `dirname /lib/modules/*/kernel/nvidia-*/bits/SHA256SUMS`
# Check nvidia_dir
[ -e $nvidia_dir/bits/SHA256SUMS ] || exit 0

if ! cmp -s $nvidia_dir/bits/SHA256SUMS $SNAP_COMMON/nvidia-driver/bits/SHA256SUMS
then
    rm -rf $SNAP_COMMON/nvidia-driver
    mkdir -p $SNAP_COMMON/nvidia-driver
    cp -r $nvidia_dir/bits $SNAP_COMMON/nvidia-driver/
    cd $SNAP_COMMON/nvidia-driver/bits
    sed -i 's|/usr/bin/ld.bfd|ld.bfd|' BUILD
    sh BUILD
fi

if snapctl is-connected modprobe-nvidia
then
    snapctl kmod insert nvidia-drm
    snapctl kmod insert nvidia-uvm
fi

if ! snapctl is-connected nvidia-support
then
   echo please connect nvidia-support
   echo attempting execution assuming devmode available
   set +e
fi

mknod -m 666 /dev/nvidia0 c 195 0
mknod -m 666 /dev/nvidiactl c 195 255
mknod -m 666 /dev/nvidia-modeset c 195 254

major=$(sed -n 's|^\([0-9]*\) nvidia-uvm$|\1|p' /proc/devices)
if [ -n "$major" ]; then
    mknod -m 666 /dev/nvidia-uvm c $major 0
    mknod -m 666 /dev/nvidia-uvm-tools c $major 1
fi
