name: nvidia-assemble
adopt-info: version
grade: devel
summary: assemble and load Nvidia drivers
description: assemble and load Nvidia drivers
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  udev-rules:
    interface: system-files
    write:
      - /etc/udev/rules.d

  modprobe:
    interface: system-files
    write:
      - /etc/modprobe.d

apps:
  nvidia-assemble:
    command: commands/nvidia-assemble
    daemon: oneshot
    plugs:
      - udev-rules
      - modprobe
      - hardware-observe

hooks:
  remove:
    plugs:
      - udev-rules
      - modprobe

parts:

  version:
    plugin: nil
    source: .
    build-packages:
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    override-stage: |
      true

  nvidia-assemble:
    plugin: dump
    source: ./nvidia-assemble/

  deps:
    plugin: nil
    build-packages:
      - dpkg-dev
    stage-packages:
      - binutils
      - nvidia-kernel-common-510-server
    stage:
      - sbin/ub-device-create
      - usr/lib/*/lib*
      - lib/modprobe.d/
      - usr/bin/*-ld.bfd
      - usr/bin/ld.bfd
      - usr/share/doc/*/changelog*
      - usr/share/doc/*/copyright
    organize:
      lib/modprobe.d/nvidia-graphics-drivers.conf: lib/modprobe.d/snap.nvidia-assemble.conf
    override-stage: |
      snapcraftctl stage
      /snap/snapcraft/current/bin/patchelf --set-rpath /snap/nvidia-assemble/current/usr/lib/$(dpkg-architecture -q DEB_HOST_MULTIARCH) $SNAPCRAFT_STAGE/sbin/ub-device-create
