#!/bin/sh
set -eux

nvidia_dir=/lib/modules/*/kernel/nvidia-*
# Check nvidia_dir
[ -e $nvidia_dir/bits/SHA256SUMS ]

if ! cmp -s $nvidia_dir/bits/SHA256SUMS $SNAP_COMMON/nvidia-driver/bits/SHA256SUMS
then
    rm -rf $SNAP_COMMON/nvidia-driver
    mkdir -p $SNAP_COMMON/nvidia-driver
    cp -r $nvidia_dir/bits $SNAP_COMMON/nvidia-driver/
    cd $SNAP_COMMON/nvidia-driver/bits
    sed -i 's|/usr/bin/ld.bfd|ld.bfd|' BUILD
    sh BUILD
fi

cp --verbose $SNAP/lib/udev/rules.d/*.rules /etc/udev/rules.d/ || echo system-files not connected
cp --verbose $SNAP/lib/modprobe.d/*.conf /etc/modprobe.d/ || echo system-files not connected

/bin/udevadm control --reload || echo Permission denied
/bin/udevadm trigger --wait-daemon --settle --type=devices --subsystem-match=pci --attr-match=vendor=0x10de --action=add || echo Permission denied
